Added 3 module tasks
js-tasks-ru/jsbasic-20230428_miracleman pull request #3
Opened 2023-05-20 12:32 UTC by miracleman1984

2023-05-20 12:33 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-05-23 15:05 UTC, SinimaWath requested changes

2023-05-27 16:31 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-05-29 13:52 UTC, SinimaWath approved these changes

2023-05-29 13:52 UTC, SinimaWath commented on 5-module/3-task/index.js
> +  lenta = document.querySelector('.carousel_inner');
`const lenta` - надо создать переменную через const

2023-05-29 13:52 UTC, SinimaWath commented on 5-module/2-task/index.js
> +  button = document.querySelector('.toggle-text-button');
`const button ` - надо создать переменную через const

2023-05-29 13:52 UTC, SinimaWath commented on 4-module/3-task/index.js
> +  tableRows = Array.from(table.rows);
`const tableRows ` - надо создать переменную через const

2023-05-29 13:53 UTC, merged